# Generated by Django 5.2.1 on 2025-05-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usercity_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercity',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
